# Generated by Django 4.2.5 on 2023-09-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_send', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(auto_now=True, null=True, verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', max_length=20, verbose_name='периодичность')),
                ('mailing_status', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена')], default='completed', max_length=20, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'настройки рассылки',
                'verbose_name_plural': 'настроек рассылки',
            },
        ),
    ]
