# Generated by Django 4.2.5 on 2023-09-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_send', '0002_mailingsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(max_length=200, verbose_name='тема письма')),
                ('body_letter', models.TextField(verbose_name='тело письма')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mail_send.serviceclient')),
            ],
            options={
                'verbose_name': 'сообщение рассылки',
                'verbose_name_plural': 'сообщений рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='дата попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('log_message', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mail_send.emailmessage')),
            ],
            options={
                'verbose_name': 'логи рассылки',
                'verbose_name_plural': 'логи рассылок',
            },
        ),
    ]
