# Generated by Django 4.2.5 on 2023-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_send', '0004_alter_emailmessage_client_alter_mailinglogs_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetup',
            name='mailing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
